name: .NET Core Desktop
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    strategy:
      matrix:
        conf: [Debug, Release]
    runs-on: windows-latest
    env:
      Solution_Name: bdd.workshop.sln
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Execute xunit tests
        run: dotnet test --filter bdd.workshop.calculator.tests.xunit

      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Conf
        env:
          Conf: ${{ matrix.conf }}